
name: Deploy to server
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - name: Execute remote SSH commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_SERVER }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_KEY }}
        script: git pull
